Feat/issue 17
frontendcafe/cmyk-lime pull request #24
Opened 2021-09-03 22:16 UTC by Lipitt

## Descripcion

commits:
created components folder, BottomNav & BottomNavButton files
created BottomNavButton component
created BottomNav component
created BottomNav & BottomNavButton style modules
added BottomNav component to index.js
added comments regarding problems in BottomNavButton.js

problemas/dudas: 

        1- si bien los links funcionan, cuando le hago hover a los links, 
            el icono del mouse no cambia. 
        2- el svg de "info padres" queda ligeramente descentrado. no quise perder
            mucho tiempo intentando alinearlo. 
        3- el import del font lo puse en BottomNavButtom.module.css, pero 
            deberia ir en el global, no?
         

## Capturas de pantalla

![image](url)

## Issue

https://github.com/frontendcafe/cmyk-lime/issues/17

2021-09-05 15:50 UTC, maxiblanco commented on components/BottomNavButton.js
> +        <Link href={route} passHref>
Agregar un solo link para todo el boton. passHref no hace falta. Necesitas un <a> element para que el link detecte el elemento correctamente.

2021-09-05 15:50 UTC, maxiblanco commented on styles/BottomNavButton.module.css
> +.text {
crear 1 solo modulo para bottom nav

2021-09-05 15:51 UTC, maxiblanco requested changes
Cambios requeridos, simplificar el bottom nav button con un solo link y centrar imagen.

2021-09-06 18:02 UTC, Lipitt commented
los cambios requeridos se han completado

2021-09-07 21:29 UTC, maxiblanco reviewed
Genial!

2021-09-08 18:55 UTC, maxiblanco approved these changes

2021-09-08 18:55 UTC, merged