feat/issue#19: creacion de componentes SVG y pruebas de animacion
frontendcafe/cmyk-lime pull request #28
Opened 2021-09-08 12:02 UTC by Duarteka

## Descripcion

Descripcion de la tarea y lo que se trabajó: 

La tarea consistía en crear una carpeta en pages y ahi crear distintas paginas por cada numero listado.
Por el momento estimo que es mas conveniente, quizás por temas de rendimiento, que las transiciones hagan el render en una sola ruta siguiendo los diferentes eventos, por el momento estoy a modo de pruebas ya que aun tengo que elaborar un mapa mental de las animaciones, por lo que si no sale bien a lo mejor si que tendré que crear una ruta por cada component.

en la carpeta components cree los componentes de los SVG, utilice la librería de svgr y svg-to-jsx ambos para optimizar la sintaxis de los SVG. También usé PropTypes para verificar dinámicamente las props de los componentes . Los componentes los estoy importando en pages/intro que es donde voy a programar la lógica de las animaciones.

Referencias:
https://www.npmjs.com/package/svg-to-jsx
https://www.framer.com/docs/
https://blog.bitsrc.io/transform-an-svg-into-a-react-component-with-svgr-8d2ba10f424c
https://www.npmjs.com/package/@svgr/cli

## Issue #19

2021-09-09 17:29 UTC, MarcosNASA commented on components/00_IntroCircle.js
> +  hidden: { y: "300px" },
Si el objetivo es que el elemento comience fuera de la pantalla, podrías probar a ponerle como valor para el eje y `100vh`. De ese modo, nos aseguramos que quede fuera de la pantalla sea cual sea el tamaño de ésta.
Si el objetivo es otro, siéntete libre de ignorar el comentario. :)

2021-09-09 17:29 UTC, MarcosNASA commented on pages/Intro.js
> +}
Aunque por ahora estén vacíos, ¿planeas utilizar estos componentes?

De lo contrario, estaría bien que los eliminases.

2021-09-09 17:29 UTC, MarcosNASA commented on styles/Intro.module.css
> +    min-height: 100vh;
Si ya estableces el height más abajo, ¿es realmente necesario este min-height establecido al mismo valor?

2021-09-09 18:11 UTC, Duarteka commented on pages/Intro.js
> +}
Si claro que los usaré, no están de adorno, quizá no utilice todos pero los que no, ya los iré borrando.

2021-09-09 18:12 UTC, Duarteka commented on styles/Intro.module.css
> +    min-height: 100vh;
Sip me has pillado, es un copia y pega mal hecho.

2021-09-09 18:22 UTC, Duarteka commented on components/00_IntroCircle.js
> +  hidden: { y: "300px" },
Tiene sentido.
Ya lo modifiqué, gracias :)

2021-09-19 14:51 UTC, maxiblanco requested changes
Error entrando a Intro pages, no encuentra componentes. Resolver errores y resubmit.

2021-09-19 14:51 UTC, maxiblanco commented on pages/Intro.js
> +import { Splash } from "/components/01_Splash";
Error cannot resolve module. Falta commitear o renombrar algo?

2021-09-22 22:06 UTC, merged