feat/issue-26: Conectar una Supabase bucket y crear un demo de audio
frontendcafe/cmyk-lime pull request #29
Opened 2021-09-08 23:21 UTC by rortan134

## Descripcion

Conectar una Supabase bucket y crear un demo de audio.
**http://localhost:3000/demos/audio**

## Capturas de pantalla

![image](url)

## Issue

https://github.com/frontendcafe/cmyk-lime/issues/26

2021-09-09 17:07 UTC, MarcosNASA commented on pages/demos/audio.js
> +  const supabase = createClient(supabaseUrl, supabaseAnonKey);
Cada vez que el componente `AudioPage` se rerenderice, volveremos a crear un cliente de supabase. Idealmente, deberías reutilizar el mismo cliente a través de toda la app.

Por ello, te propongo que crees un fichero llamado `supabase.js` cuyo contenido sea estas tres líneas y que exporte supabase, para que así puedas importarlo en el resto de los componentes que lo necesite.

```js
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_KEY;
const supabase = createClient(supabaseUrl, supabaseAnonKey);
export { supabase }
```

2021-09-09 17:07 UTC, MarcosNASA commented on pages/demos/audio.js
> +      console.log(soundUrl);
Una vez terminamos de debuggear, sería oportuno eliminar los `console.log`.

2021-09-09 17:07 UTC, MarcosNASA commented on pages/demos/audio.js
> +    const audioDiv = document.querySelector('.videoAudio');
Te animo a usar una ref en lugar de hacer una `query` del elemento:
```js
const audioRef = useRef()
...
function handleAudio() {
  const audioElement = audioRef.current
  ...
}

return (
  ...
  <audio ... ref={audioRef}>
    ...
  </audio>
  ...
)
```

2021-09-09 17:07 UTC, MarcosNASA commented on styles/Audio.module.css
> +  flex-direction: column;
En la mayoría de las ocasiones, estas 4 líneas pueden reemplazarse por sólo 2:
```css
display: grid;
place-items: center;
```

2021-09-09 17:52 UTC, rortan134 commented on pages/demos/audio.js
> +    const audioDiv = document.querySelector('.videoAudio');
Te importaría explicar por qué?
Por lo que veo usaría más líneas, pero no estoy seguro de qué uso tendría aparte de llamar al elemento

2021-09-09 18:19 UTC, MarcosNASA commented on pages/demos/audio.js
> +    const audioDiv = document.querySelector('.videoAudio');
¡Claro! Las ref son la forma propia en React de acceder a los elementos del DOM. Hay varias razones por las que son 
preferibles. Éstas son algunas de las que se me ocurren de primeras:

1. Las enlazas al elemento una vez y puedes acceder a ellas siempre, aunque el componente se renderice más veces. Sin embargo, con `document.querySelector` estás buscando un elemento en el DOM cada vez que ejecutas la función `handleAudio`. Con una ref, no tienes siquiera que buscarlo.
2. Pese a que parezca más código, es más declarativo. En la solución, en ningún momento digo "ve a buscar un elemento al DOM que tenga X clase". Simplemente lo enlazo en el JSX y tengo acceso a él.
3. Te aseguras de que te devuelve el elemento que necesitas. Si algún otro compañero añade una clase `videoAudio` a un elemento que se renderice antes, `document.querySelector` te devolverá dicho elemento en lugar del tuyo.

Si sigues teniendo dudas, ¡coméntamelas!

2021-09-10 21:25 UTC, maxiblanco requested changes
Usar useRef para tomar el elemento del DOM y crear un unico supabase plugin para toda la app.
Muy bueno el audio! Con esto confirmamos que podemos tener narraciones! Gracias!

2024-03-19 10:26 UTC, closed without merging